# Generated by Django 3.1 on 2020-08-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
