# Generated by Django 3.1 on 2020-08-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_specialty_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.CharField(max_length=32),
        ),
    ]
