# Generated by Django 3.1 on 2020-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_auto_20200819_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
                ('specialty', models.CharField(max_length=32)),
                ('grade', models.CharField(max_length=32)),
                ('education', models.CharField(max_length=32)),
                ('experience', models.CharField(max_length=32)),
                ('portfolio', models.CharField(max_length=32)),
            ],
        ),
    ]
