# Generated by Django 3.1 on 2020-08-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_auto_20200821_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
