# Generated by Django 3.1 on 2020-08-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='usere',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
