# Generated by Django 3.1 on 2020-08-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_auto_20200822_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usere',
            new_name='user',
        ),
    ]
