# Generated by Django 3.1 on 2020-08-22 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0018_auto_20200822_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='profile_pic',
            field=models.ImageField(blank=True, default='check.png', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='check.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='specialty',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
