# Generated by Django 3.1 on 2020-08-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_auto_20200822_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
