# Generated by Django 3.1 on 2020-08-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
