# Generated by Django 3.1 on 2020-08-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0021_auto_20200822_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
