# Generated by Django 3.1 on 2020-08-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0029_auto_20200825_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='company.png', null=True, upload_to=''),
        ),
    ]
