# Generated by Django 3.1 on 2020-08-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0031_auto_20200826_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(default=12, max_length=32),
            preserve_default=False,
        ),
    ]
