# Generated by Django 3.1 on 2020-08-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0032_vacancy_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
