# Generated by Django 3.1 on 2020-08-28 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0034_statusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='vacancies.statusmodel'),
            preserve_default=False,
        ),
    ]



