# Generated by Django 3.1 on 2020-08-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0037_grademodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='grademodel',
            name='code',
            field=models.CharField(default=12, max_length=32),
            preserve_default=False,
        ),
    ]
