# Generated by Django 3.1 on 2020-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0046_auto_20200904_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(db_index=True, max_length=124),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(db_index=True, max_length=124),
        ),
    ]
