# Generated by Django 3.1 on 2020-09-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0048_auto_20200909_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
