# Generated by Django 3.1 on 2020-09-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0051_auto_20200910_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
